# Generated by Django 6.0.6 on 2026-07-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='github_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='live_link',
            field=models.URLField(blank=True),
        ),
    ]
