# Generated by Django 6.0.6 on 2026-07-08 03:50

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('organization', models.CharField(max_length=150)),
                ('year', models.CharField(max_length=50)),
                ('verification_link', models.URLField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=150)),
                ('college', models.CharField(max_length=150)),
                ('date_range', models.CharField(max_length=50)),
                ('cgpa', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=100)),
                ('availability', models.CharField(default='Freelance / Full-time', max_length=100)),
                ('tagline', models.TextField()),
                ('bio', models.TextField()),
                ('professions', models.CharField(help_text='Comma-separated list of professions for the typing animation', max_length=255)),
                ('github_link', models.URLField(blank=True)),
                ('linkedin_link', models.URLField(blank=True)),
                ('resume_url', models.URLField(blank=True, help_text='Cloudinary raw URL or external URL for resume PDF')),
                ('profile_photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='challenges',
            field=models.TextField(blank=True, help_text='One challenge/solution per line'),
        ),
        migrations.AddField(
            model_name='job',
            name='features',
            field=models.TextField(blank=True, help_text='One feature per line'),
        ),
        migrations.AddField(
            model_name='job',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='published_date',
            field=models.CharField(default='June 2026', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress')], default='Completed', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='jobs.skills'),
        ),
        migrations.AddField(
            model_name='skills',
            name='icon_class',
            field=models.CharField(default='fa-solid fa-code', help_text="FontAwesome icon class (e.g. 'fa-brands fa-python')", max_length=100),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(default='Present', max_length=50)),
                ('description', models.TextField()),
                ('technologies', models.ManyToManyField(blank=True, related_name='experiences', to='jobs.skills')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='jobs.job')),
            ],
        ),
    ]
