# Generated by Django 6.0.6 on 2026-07-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='job',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which projects are displayed'),
        ),
    ]
