# Generated by Django 6.0.6 on 2026-07-08 04:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_job_options_job_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='resume_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload your resume PDF to Cloudinary', max_length=255, null=True),
        ),
    ]
